"""checklist_progress_to_production_tasks

Revision ID: dbe521559d39
Revises: ba1ba208e479
Create Date: 2025-06-02 13:19:57.336853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe521559d39'
down_revision = 'ba1ba208e479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_tasks', sa.Column('checklist_progress', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_tasks', 'checklist_progress')
    # ### end Alembic commands ###
